# Generated by Django 2.2.6 on 2019-10-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20191020_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentformsave',
            old_name='studentformsave',
            new_name='student_name',
        ),
        migrations.CreateModel(
            name='student_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutionfee', models.IntegerField()),
                ('bookfree', models.IntegerField()),
                ('studentformsave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studenaccountfile', to='projectapp.studentformsave')),
            ],
        ),
    ]
